api_platform:
    title: Sejour+ Admin
    version: 1.0.0
    docs_formats:
        jsonld: ['application/ld+json']
        html: ['text/html']
    patch_formats:
        json: ['application/merge-patch+json']
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
