name: sejour-plus-backend

services:
  api:
    build:
      context: .
      dockerfile: dockerfile.prod
    ports:
      - "9002:80"   # Apache écoute toujours en interne sur 80 mais mappé sur 9002
    environment:
      APP_ENV: prod
      DATABASE_URL: postgres://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-!ChangeMe!}@database:5432/${POSTGRES_DB:-app}
    restart: always
    depends_on:
      - database

  database:
    image: postgres:${POSTGRES_VERSION:-16}
    container_name: postgres_db
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-app}
      - POSTGRES_USER=${POSTGRES_USER:-app}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-!ChangeMe!}
    volumes:
      - database_data:/var/lib/postgresql/data
    restart: always

volumes:
  database_data:
    driver: local
